/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


 /* Includes the header in the wrapper code */
 #include "levtree.h"
 

#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1maxsize_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->maxsize = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1maxsize_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->maxsize);
  {
    index_t * resultptr = (index_t *) malloc(sizeof(index_t));
    memmove(resultptr, &result, sizeof(index_t));
    *(index_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1allocated_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t arg2 ;
  byte_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(byte_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->allocated = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1allocated_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->allocated);
  {
    byte_t * resultptr = (byte_t *) malloc(sizeof(byte_t));
    memmove(resultptr, &result, sizeof(byte_t));
    *(byte_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1torealloc_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t arg2 ;
  byte_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(byte_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->torealloc = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1torealloc_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->torealloc);
  {
    byte_t * resultptr = (byte_t *) malloc(sizeof(byte_t));
    memmove(resultptr, &result, sizeof(byte_t));
    *(byte_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1nodes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  levnode *arg2 = (levnode *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  arg2 = *(levnode **)&jarg2; 
  if (arg1) (arg1)->nodes = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1nodes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  levnode *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result = (levnode *) ((arg1)->nodes);
  *(levnode **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1node_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->node_count = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1node_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->node_count);
  {
    index_t * resultptr = (index_t *) malloc(sizeof(index_t));
    memmove(resultptr, &result, sizeof(index_t));
    *(index_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1node_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->node_size = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1node_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->node_size);
  {
    index_t * resultptr = (index_t *) malloc(sizeof(index_t));
    memmove(resultptr, &result, sizeof(index_t));
    *(index_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1entries_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t *arg2 = (index_t *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  arg2 = *(index_t **)&jarg2; 
  if (arg1) (arg1)->entries = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1entries_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result = (index_t *) ((arg1)->entries);
  *(index_t **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1entry_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->entry_count = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1entry_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->entry_count);
  {
    index_t * resultptr = (index_t *) malloc(sizeof(index_t));
    memmove(resultptr, &result, sizeof(index_t));
    *(index_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1entry_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg2 = *argp2; 
  if (arg1) (arg1)->entry_size = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1entry_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  index_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result =  ((arg1)->entry_size);
  {
    index_t * resultptr = (index_t *) malloc(sizeof(index_t));
    memmove(resultptr, &result, sizeof(index_t));
    *(index_t **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1standing_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  levtree_standing *arg2 = (levtree_standing *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  arg2 = *(levtree_standing **)&jarg2; 
  if (arg1) (arg1)->standing = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1standing_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  levtree_standing *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result = (levtree_standing *) ((arg1)->standing);
  *(levtree_standing **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1checker_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t (*arg2)(char,char) = (byte_t (*)(char,char)) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  arg2 = *(byte_t (**)(char,char))&jarg2; 
  if (arg1) (arg1)->checker = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1checker_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  byte_t (*result)(char,char) = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result = (byte_t (*)(char,char)) ((arg1)->checker);
  *(byte_t (**)(char,char))&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1distance_1calculator_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  void (*arg2)(levtree *,char const *,index_t,index_t *,index_t,index_t) = (void (*)(levtree *,char const *,index_t,index_t *,index_t,index_t)) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  arg2 = *(void (**)(levtree *,char const *,index_t,index_t *,index_t,index_t))&jarg2; 
  if (arg1) (arg1)->distance_calculator = arg2;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1distance_1calculator_1get(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  struct levtree *arg1 = (struct levtree *) 0 ;
  void (*result)(levtree *,char const *,index_t,index_t *,index_t,index_t) = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  result = (void (*)(levtree *,char const *,index_t,index_t *,index_t,index_t)) ((arg1)->distance_calculator);
  *(void (**)(levtree *,char const *,index_t,index_t *,index_t,index_t))&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_new_1levtree(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct levtree *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct levtree *)calloc(1, sizeof(struct levtree));
  *(struct levtree **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_delete_1levtree(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct levtree *arg1 = (struct levtree *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct levtree **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1init(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  levtree *arg1 = (levtree *) 0 ;
  char **arg2 = (char **) 0 ;
  index_t arg3 ;
  index_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  arg2 = *(char ***)&jarg2; 
  argp3 = *(index_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg3 = *argp3; 
  levtree_init(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1free(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  levtree *arg1 = (levtree *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  levtree_free(arg1);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1search(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  levtree *arg1 = (levtree *) 0 ;
  char *arg2 = (char *) 0 ;
  index_t arg3 ;
  index_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  argp3 = *(index_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg3 = *argp3; 
  levtree_search(arg1,(char const *)arg2,arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1set_1algorithm(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  levtree *arg1 = (levtree *) 0 ;
  levtree_algorithm arg2 ;
  levtree_algorithm *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  argp2 = *(levtree_algorithm **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null levtree_algorithm");
    return ;
  }
  arg2 = *argp2; 
  levtree_set_algorithm(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1set_1case_1sensitive(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  levtree *arg1 = (levtree *) 0 ;
  byte_t arg2 ;
  byte_t *argp2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  argp2 = *(byte_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null byte_t");
    return ;
  }
  arg2 = *argp2; 
  levtree_set_case_sensitive(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_LevtreeJNI_levtree_1add_1word(JNIEnv *jenv, jclass jcls, jlong jarg1, jstring jarg2, jlong jarg3) {
  levtree *arg1 = (levtree *) 0 ;
  char *arg2 = (char *) 0 ;
  index_t arg3 ;
  index_t *argp3 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  argp3 = *(index_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return ;
  }
  arg3 = *argp3; 
  levtree_add_word(arg1,(char const *)arg2,arg3);
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jlong JNICALL Java_LevtreeJNI_levtree_1get_1result(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  levtree *arg1 = (levtree *) 0 ;
  index_t arg2 ;
  index_t *argp2 ;
  levtree_result result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(levtree **)&jarg1; 
  argp2 = *(index_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null index_t");
    return 0;
  }
  arg2 = *argp2; 
  result = levtree_get_result(arg1,arg2);
  {
    levtree_result * resultptr = (levtree_result *) malloc(sizeof(levtree_result));
    memmove(resultptr, &result, sizeof(levtree_result));
    *(levtree_result **)&jresult = resultptr;
  }
  return jresult;
}


#ifdef __cplusplus
}
#endif

