# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_levtree')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_levtree')
    _levtree = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_levtree', [dirname(__file__)])
        except ImportError:
            import _levtree
            return _levtree
        if fp is not None:
            try:
                _mod = imp.load_module('_levtree', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _levtree = swig_import_helper()
    del swig_import_helper
else:
    import _levtree
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _levtree.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _levtree.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _levtree.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _levtree.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _levtree.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _levtree.SwigPyIterator_equal(self, x)

    def copy(self):
        return _levtree.SwigPyIterator_copy(self)

    def next(self):
        return _levtree.SwigPyIterator_next(self)

    def __next__(self):
        return _levtree.SwigPyIterator___next__(self)

    def previous(self):
        return _levtree.SwigPyIterator_previous(self)

    def advance(self, n):
        return _levtree.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _levtree.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _levtree.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _levtree.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _levtree.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _levtree.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _levtree.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _levtree.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class ResultVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ResultVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ResultVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _levtree.ResultVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _levtree.ResultVector___nonzero__(self)

    def __bool__(self):
        return _levtree.ResultVector___bool__(self)

    def __len__(self):
        return _levtree.ResultVector___len__(self)

    def __getslice__(self, i, j):
        return _levtree.ResultVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _levtree.ResultVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _levtree.ResultVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _levtree.ResultVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _levtree.ResultVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _levtree.ResultVector___setitem__(self, *args)

    def pop(self):
        return _levtree.ResultVector_pop(self)

    def append(self, x):
        return _levtree.ResultVector_append(self, x)

    def empty(self):
        return _levtree.ResultVector_empty(self)

    def size(self):
        return _levtree.ResultVector_size(self)

    def swap(self, v):
        return _levtree.ResultVector_swap(self, v)

    def begin(self):
        return _levtree.ResultVector_begin(self)

    def end(self):
        return _levtree.ResultVector_end(self)

    def rbegin(self):
        return _levtree.ResultVector_rbegin(self)

    def rend(self):
        return _levtree.ResultVector_rend(self)

    def clear(self):
        return _levtree.ResultVector_clear(self)

    def get_allocator(self):
        return _levtree.ResultVector_get_allocator(self)

    def pop_back(self):
        return _levtree.ResultVector_pop_back(self)

    def erase(self, *args):
        return _levtree.ResultVector_erase(self, *args)

    def __init__(self, *args):
        this = _levtree.new_ResultVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _levtree.ResultVector_push_back(self, x)

    def front(self):
        return _levtree.ResultVector_front(self)

    def back(self):
        return _levtree.ResultVector_back(self)

    def assign(self, n, x):
        return _levtree.ResultVector_assign(self, n, x)

    def resize(self, *args):
        return _levtree.ResultVector_resize(self, *args)

    def insert(self, *args):
        return _levtree.ResultVector_insert(self, *args)

    def reserve(self, n):
        return _levtree.ResultVector_reserve(self, n)

    def capacity(self):
        return _levtree.ResultVector_capacity(self)
    __swig_destroy__ = _levtree.delete_ResultVector
    __del__ = lambda self: None
ResultVector_swigregister = _levtree.ResultVector_swigregister
ResultVector_swigregister(ResultVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _levtree.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _levtree.StringVector___nonzero__(self)

    def __bool__(self):
        return _levtree.StringVector___bool__(self)

    def __len__(self):
        return _levtree.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _levtree.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _levtree.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _levtree.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _levtree.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _levtree.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _levtree.StringVector___setitem__(self, *args)

    def pop(self):
        return _levtree.StringVector_pop(self)

    def append(self, x):
        return _levtree.StringVector_append(self, x)

    def empty(self):
        return _levtree.StringVector_empty(self)

    def size(self):
        return _levtree.StringVector_size(self)

    def swap(self, v):
        return _levtree.StringVector_swap(self, v)

    def begin(self):
        return _levtree.StringVector_begin(self)

    def end(self):
        return _levtree.StringVector_end(self)

    def rbegin(self):
        return _levtree.StringVector_rbegin(self)

    def rend(self):
        return _levtree.StringVector_rend(self)

    def clear(self):
        return _levtree.StringVector_clear(self)

    def get_allocator(self):
        return _levtree.StringVector_get_allocator(self)

    def pop_back(self):
        return _levtree.StringVector_pop_back(self)

    def erase(self, *args):
        return _levtree.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _levtree.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _levtree.StringVector_push_back(self, x)

    def front(self):
        return _levtree.StringVector_front(self)

    def back(self):
        return _levtree.StringVector_back(self)

    def assign(self, n, x):
        return _levtree.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _levtree.StringVector_resize(self, *args)

    def insert(self, *args):
        return _levtree.StringVector_insert(self, *args)

    def reserve(self, n):
        return _levtree.StringVector_reserve(self, n)

    def capacity(self):
        return _levtree.StringVector_capacity(self)
    __swig_destroy__ = _levtree.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _levtree.StringVector_swigregister
StringVector_swigregister(StringVector)

LEVENSHTEIN = _levtree.LEVENSHTEIN
DAMERAU_LEVENSHTEIN = _levtree.DAMERAU_LEVENSHTEIN
class LevtreeResult(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, LevtreeResult, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, LevtreeResult, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _levtree.new_LevtreeResult(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["word"] = _levtree.LevtreeResult_word_set
    __swig_getmethods__["word"] = _levtree.LevtreeResult_word_get
    if _newclass:
        word = _swig_property(_levtree.LevtreeResult_word_get, _levtree.LevtreeResult_word_set)
    __swig_setmethods__["id"] = _levtree.LevtreeResult_id_set
    __swig_getmethods__["id"] = _levtree.LevtreeResult_id_get
    if _newclass:
        id = _swig_property(_levtree.LevtreeResult_id_get, _levtree.LevtreeResult_id_set)
    __swig_setmethods__["distance"] = _levtree.LevtreeResult_distance_set
    __swig_getmethods__["distance"] = _levtree.LevtreeResult_distance_get
    if _newclass:
        distance = _swig_property(_levtree.LevtreeResult_distance_get, _levtree.LevtreeResult_distance_set)
    __swig_destroy__ = _levtree.delete_LevtreeResult
    __del__ = lambda self: None
LevtreeResult_swigregister = _levtree.LevtreeResult_swigregister
LevtreeResult_swigregister(LevtreeResult)

class Levtree(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Levtree, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Levtree, name)
    __repr__ = _swig_repr

    def addWord(self, word):
        return _levtree.Levtree_addWord(self, word)

    def getWord(self, id):
        return _levtree.Levtree_getWord(self, id)

    def __init__(self, *args):
        this = _levtree.new_Levtree(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _levtree.delete_Levtree
    __del__ = lambda self: None

    def search(self, text, number_of_matches=4):
        return _levtree.Levtree_search(self, text, number_of_matches)

    def setCaseSensitive(self, b):
        return _levtree.Levtree_setCaseSensitive(self, b)

    def setAlgorithm(self, algo):
        return _levtree.Levtree_setAlgorithm(self, algo)
Levtree_swigregister = _levtree.Levtree_swigregister
Levtree_swigregister(Levtree)

# This file is compatible with both classic and new-style classes.


